services:
  - type: web
    name: hospital-management
    env: python
    buildCommand: cd Hospital_Management && pip install -r requirements.txt
    startCommand: cd Hospital_Management && gunicorn Hospital_Management.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: Hospital_Management.settings
